### ISSUE TITLE
Initial Commit, React Frontend

### ISSUE THREAD

**Issue by Lucaslah** [CSSUDII/api-frontend#1]
# React Frontend

## TODO:

- [x] Get started on Frontend
- [x] Commit Frontend
- [ ] Requests for Frontend (user page)
- [ ] Index Page
- [x] Requests for user signup
- [x] GET requests for Auth token (50%)
- [ ] GET requests for Auth token (100%)
- [x] User Login Page
- [ ] 100% Working
- [] Wrap 100% of the API (https://github.com/CSSUDII/public)

**Comment by Lucaslah** [comment]
@cssudii-bot fix
